import Head from "next/head";
import config from "../config";

export const Meta = () => {
  return (
    <Head>
      <title>Music Playground</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href={`${config.baseUrl}/favicon.ico`} />
    </Head>
  );
};
